name: '#MichaelDeveloper'
description: 'Vamos falar sobre código!'
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mclexr.gitgub.io'
google_analytics: 'UA-72547169-1'

# Details for the RSS feed generator
url: 'http://mclexr.github.io'

author:
    name: Michael Fidelis
    thumb: /assets/images/profile.jpg
    bio: Desenvolvedor fullstack, entusiasta de novas ttecnologias e apaixonado pelo que faz!.
    url:
        twitter: 'https://twitter.com/mclexr'
        linkedin: 'http://br.linkedin.com/in/mclexr'
        email: 'mclexr@gmail.com'

urls:
    about: /sobre

img_path: /assets/images/
