name: Michael Fidelis
description: FullStack Developer

markdown: redcarpet
highlighter: pygments
paginate: 15
baseurl: /
domain_name: 'http://mclexr.github.io'
google_analytics: 'UA-72547169-1'

# Details for the RSS feed generator
url: 'http://mclexr.github.io'

author:
    name: Michael Fidelis
    thumb: /assets/images/profile.jpg
    bio: Desenvolvedor fullstack, entusiasta de novas tecnologias e apaixonado pelo que faço! Sou péssimo com design (confesso), mas adoro pôr a mão na massa. Codificar, interagir, ajudar no desenho da solução e, claro, ver as coisas funcionando. Vez ou outra ajudo uma galera a aprender a programar, seja com mini cursos, projetos ou um bate papo.
    url:
        twitter: 'https://twitter.com/mclexr'
        linkedin: 'http://br.linkedin.com/in/mclexr'
        email: 'mclexr@gmail.com'

urls:
    about: /sobre

img_path: /assets/images/
