name: Blog do Michael Fidelis
description: FullStack Developer

markdown: kramdown
highlighter: rouge
paginate: 15
baseurl: /
domain_name: 'http://michaelfidelis.github.io'
google_analytics: 'UA-72547169-1'
permalink: '/:categories/:title/'
# Details for the RSS feed generator
url: 'http://michaelfidelis.github.io'

author:
    name: Michael Fidelis
    thumb: /assets/images/profile.jpg
    bio: Desenvolvedor fullstack, entusiasta de novas tecnologias e apaixonado pelo que faço! Codificar, interagir, ajudar no desenho da solução e, claro, ver as coisas funcionando.
    email: 'mclexr@gmail.com'
    url:
        twitter: 'https://twitter.com/mclexr'
        linkedin: 'http://br.linkedin.com/in/mclexr'
        email: 'mclexr@gmail.com'

urls:
    about: /sobre
    demo: /demos/

img_path: /assets/images/

gems: [jekyll-paginate]
